In [ ]:
import sys

# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")


Hello, World!
Python version: 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]


In [ ]:
# Mutable Data Type Example (List)
my_list = [1, 2, 3]
print("Original List:", my_list)
# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)

# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)


Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


In [ ]:
age = 23  # int
pi = 3.14  # float
temperature = -5.5  # float

print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))


data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


In [ ]:
name = "Alice"
greeting = "Hello"  # Changed to use regular double quotes
address = "123 Main St"

print("data type of the variable name = ", type(name))
print("data type of the variable greeting = ", type(greeting))
print("data type of the variable address = ", type(address))

# Slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])

# Slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])


data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


In [ ]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

In [ ]:
person = {'name': 'John', 'age': 30, 'city': 'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))


Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


In [ ]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


In [ ]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


In [ ]:
result = None

In [ ]:
num = 10
if num > 0:
    print("Positive")
elif num == 0:
    print("Zero")
else:
    print("Non-positive")


Positive


In [ ]:
x = 5
y = 10

if x > 0 and y < 20:
    print("Both conditions are true")

if x > 0 or y > 20:
    print("At least one condition is true")

if not x == 0:
    print("x is not equal to 0")


Both conditions are true
At least one condition is true
x is not equal to 0


In [ ]:
# Define two boolean variables
a = True
b = False

# Using the 'and' operator
if a and b:
    print("Both a and b are True")
else:
    print("Either a or b is False")  # This will be printed

# Using the 'or' operator
if a or b:
    print("At least one of a or b is True")  # This will be printed
else:
    print("Both a and b are False")

# Using the 'not' operator
if not a:
    print("a is False")  # This will not be printed
else:
    print("a is True")  # This will be printed


Either a or b is False
At least one of a or b is True
a is True


In [ ]:
# For loop:
fruits = ["apple", "banana", "cherry"]
print (fruits[0][3])
for fruit in fruits:
    print(fruit)

# While loop:
count = 0
while count < 5:
    print("Count is:", count)
    count += 1

# Break
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
    print(fruit)
    if fruit == "apple":
        break  # Break the loop when "apple" is encountered

# Continue
print("loop 2")
for fruit in fruits:
    if fruit == "apple":
        continue  # Skip the "apple" and continue the loop
    else:
        print(fruit)


l
apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop 2
banana
orange


In [ ]:
def add_binary(a, b):
    '''
    Returns the sum of two decimal numbers in binary digits.
    Parameters:
    a (int): A decimal integer
    b (int): Another decimal integer
    Returns:
    binary_sum (str): Binary string of the sum of a and b
    '''
    binary_sum = bin(a + b)[2:]  # bin() returns a binary string starting with '0b', we slice it off with [2:]
    return binary_sum


In [ ]:
print("Hello, World!") # Output: Hello, World!
length = len("Hello") # Output: 5
data_type = type(42) # Output: <class ’int’>
total = sum([1, 2, 3]) # Output: 6

Hello, World!


In [ ]:
# str.upper(): Converts all characters in a string to uppercase.
message = "hello".upper() # Output: "HELLO"
# list.append(): Adds an element to the end of a list.
fruits = ["apple", "banana"]
fruits.append("cherry") # Output: ["apple", "banana", "cherry"]
# dict.get(): Returns the value associated with a key in a dictionary.
info = {"name": "Alice", "age": 25}
age = info.get("age") # Output: 25

In [ ]:
def temperature_converter():
    """
    Converts temperature between Celsius and Fahrenheit.
    This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
    Fahrenheit to Celsius) and then asks for the temperature value. It calculates and returns the converted temperature.
    Returns:
    float: The converted temperature value.
    """
    print("Choose conversion type:")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")

    # Get conversion choice from user
    choice = input("Enter 1 or 2: ")

    if choice == "1":
        # Celsius to Fahrenheit conversion
        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius}C is equal to {fahrenheit}F")
        return fahrenheit

    elif choice == "2":
        # Fahrenheit to Celsius conversion
        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit}F is equal to {celsius}C")
        return celsius

    else:
        print("Invalid choice. Please enter 1 or 2.")
        return None

# Call the function
temperature_converter()


Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 1
Enter temperature in Celsius: 25
25.0C is equal to 77.0F


77.0

In [ ]:
x = 10  # Global Variable.

def print_global():
    print(x)  # Accessing global variable

print_global()  # Output: 10


10


In [ ]:
def print_local():
    y = 5  # Local variable
    print(y)  # Prints the value of y inside the function

print_local()



5


In [ ]:
x = 10  # Global variable

def modify_global():
    global x  # Declaring x as global
    x = 20  # Modifying global x

modify_global()
print(x)  # Output: 20


20


Task1

In [ ]:
def length_converter(value, conversion_type):
    """
    Converts between meters and feet.

    Parameters:
    value (float): The value to be converted.
    conversion_type (str): The type of conversion ('m_to_ft' or 'ft_to_m').

    Returns:
    float: The converted value.
    """
    if conversion_type == 'm_to_ft':
        return value * 3.28084  # Convert meters to feet
    elif conversion_type == 'ft_to_m':
        return value / 3.28084  # Convert feet to meters
    else:
        raise ValueError("Unsupported conversion type for length")

def weight_converter(value, conversion_type):
    """
    Converts between kilograms and pounds.

    Parameters:
    value (float): The value to be converted.
    conversion_type (str): The type of conversion ('kg_to_lbs' or 'lbs_to_kg').

    Returns:
    float: The converted value.
    """
    if conversion_type == 'kg_to_lbs':
        return value * 2.20462  # Convert kilograms to pounds
    elif conversion_type == 'lbs_to_kg':
        return value / 2.20462  # Convert pounds to kilograms
    else:
        raise ValueError("Unsupported conversion type for weight")

def volume_converter(value, conversion_type):
    """
    Converts between liters and gallons.

    Parameters:
    value (float): The value to be converted.
    conversion_type (str): The type of conversion ('L_to_gal' or 'gal_to_L').

    Returns:
    float: The converted value.
    """
    if conversion_type == 'L_to_gal':
        return value * 0.264172  # Convert liters to gallons
    elif conversion_type == 'gal_to_L':
        return value / 0.264172  # Convert gallons to liters
    else:
        raise ValueError("Unsupported conversion type for volume")

def main():
    """
    Main function to drive the unit conversion program.
    Prompts the user to choose the conversion type, then performs the conversion.
    """
    print("Welcome to the Unit Converter!")
    print("Choose a conversion type:")
    print("1. Length (meters to feet, feet to meters)")
    print("2. Weight (kilograms to pounds, pounds to kilograms)")
    print("3. Volume (liters to gallons, gallons to liters)")

    # Get conversion type choice from the user
    try:
        choice = int(input("Enter 1, 2, or 3: "))

        if choice == 1:
            print("Length conversion:")
            conversion_type = input("Enter 'm_to_ft' for meters to feet or 'ft_to_m' for feet to meters: ")
            value = float(input("Enter the value to be converted: "))
            result = length_converter(value, conversion_type)
            print(f"Converted value: {result}")

        elif choice == 2:
            print("Weight conversion:")
            conversion_type = input("Enter 'kg_to_lbs' for kilograms to pounds or 'lbs_to_kg' for pounds to kilograms: ")
            value = float(input("Enter the value to be converted: "))
            result = weight_converter(value, conversion_type)
            print(f"Converted value: {result}")

        elif choice == 3:
            print("Volume conversion:")
            conversion_type = input("Enter 'L_to_gal' for liters to gallons or 'gal_to_L' for gallons to liters: ")
            value = float(input("Enter the value to be converted: "))
            result = volume_converter(value, conversion_type)
            print(f"Converted value: {result}")

        else:
            print("Invalid choice. Please select 1, 2, or 3.")

    except ValueError as e:
        print(f"Error: {e}. Please enter valid numbers and conversion types.")

if __name__ == "__main__":
    main()


Welcome to the Unit Converter!
Choose a conversion type:
1. Length (meters to feet, feet to meters)
2. Weight (kilograms to pounds, pounds to kilograms)
3. Volume (liters to gallons, gallons to liters)
Enter 1, 2, or 3: 3
Volume conversion:
Enter 'L_to_gal' for liters to gallons or 'gal_to_L' for gallons to liters: 30
Enter the value to be converted: 5
Error: Unsupported conversion type for volume. Please enter valid numbers and conversion types.


taks2

In [ ]:
def find_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

def find_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers.
    """
    if len(numbers) == 0:
        raise ValueError("The list is empty, so the average cannot be calculated.")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The maximum value in the list.
    """
    if len(numbers) == 0:
        raise ValueError("The list is empty, so the maximum cannot be found.")
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The minimum value in the list.
    """
    if len(numbers) == 0:
        raise ValueError("The list is empty, so the minimum cannot be found.")
    return min(numbers)

def main():
    """
    Main function to drive the mathematical operations program.
    Prompts the user to choose an operation and then performs the selected operation on a list of numbers.
    """
    print("Welcome to the Mathematical Operations Program!")
    print("Choose an operation:")
    print("1. Sum of the numbers")
    print("2. Average of the numbers")
    print("3. Maximum of the numbers")
    print("4. Minimum of the numbers")

    try:
        # Get operation choice from the user
        choice = int(input("Enter 1, 2, 3, or 4: "))

        # Get the list of numbers from the user
        numbers_input = input("Enter a list of numbers (separated by spaces): ")
        numbers = [float(num) for num in numbers_input.split()]

        # Perform the selected operation
        if choice == 1:
            result = find_sum(numbers)
            print(f"The sum of the numbers is: {result}")

        elif choice == 2:
            result = find_average(numbers)
            print(f"The average of the numbers is: {result}")

        elif choice == 3:
            result = find_maximum(numbers)
            print(f"The maximum number is: {result}")

        elif choice == 4:
            result = find_minimum(numbers)
            print(f"The minimum number is: {result}")

        else:
            print("Invalid choice. Please enter a number between 1 and 4.")

    except ValueError as e:
        print(f"Error: {e}. Please enter valid numbers and operation choices.")

if __name__ == "__main__":
    main()


Welcome to the Mathematical Operations Program!
Choose an operation:
1. Sum of the numbers
2. Average of the numbers
3. Maximum of the numbers
4. Minimum of the numbers
Enter 1, 2, 3, or 4: 2
Enter a list of numbers (separated by spaces): 3
The average of the numbers is: 3.0


task 4.2

In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Parameters:
    lst (list): A list of elements.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]  # Slicing the list to get every other element

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(input_list)
print(f"Original list: {input_list}")
print(f"Every other element: {result}")


Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]


In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the list starting from index 'start' and ending at index 'end' (inclusive).

    Parameters:
    lst (list): The original list from which to extract the sublist.
    start (int): The starting index of the sublist (inclusive).
    end (int): The ending index of the sublist (inclusive).

    Returns:
    list: The sublist from the 'start' index to the 'end' index.
    """
    return lst[start:end+1]  # Slicing the list from start to end (inclusive)

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
result = get_sublist(input_list, start_index, end_index)
print(f"Original list: {input_list}")
print(f"Sublist from index {start_index} to {end_index}: {result}")


Original list: [1, 2, 3, 4, 5, 6]
Sublist from index 2 to 4: [3, 4, 5]


In [ ]:
def reverse_list(lst):
    """
    Reverses the given list using slicing.

    Parameters:
    lst (list): The list to be reversed.

    Returns:
    list: The reversed list.
    """
    return lst[::-1]  # Reverses the list using slicing

# Example usage:
input_list = [1, 2, 3, 4, 5]
result = reverse_list(input_list)
print(f"Original list: {input_list}")
print(f"Reversed list: {result}")


Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements of the given list and returns the resulting sublist.

    Parameters:
    lst (list): The original list.

    Returns:
    list: The sublist without the first and last elements.
    """
    return lst[1:-1]  # Slicing the list to exclude the first and last elements

# Example usage:
input_list = [1, 2, 3, 4, 5]
result = remove_first_last(input_list)
print(f"Original list: {input_list}")
print(f"List without the first and last elements: {result}")


Original list: [1, 2, 3, 4, 5]
List without the first and last elements: [2, 3, 4]


In [ ]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from the given list using slicing.

    Parameters:
    lst (list): The original list from which elements are extracted.
    n (int): The number of elements to extract from the beginning of the list.

    Returns:
    list: A list containing the first n elements of the original list.
    """
    return lst[:n]  # Slicing the list to get the first n elements

# Example usage:
input_list = [1, 2, 3, 4, 5]
n = 3
result = get_first_n(input_list, n)
print(f"Original list: {input_list}")
print(f"The first {n} elements: {result}")


Original list: [1, 2, 3, 4, 5]
The first 3 elements: [1, 2, 3]


In [ ]:
def get_last_n(lst, n):
    """
    Extracts the last n elements from the given list using slicing.

    Parameters:
    lst (list): The original list from which elements are extracted.
    n (int): The number of elements to extract from the end of the list.

    Returns:
    list: A list containing the last n elements of the original list.
    """
    return lst[-n:]  # Slicing the list to get the last n elements

# Example usage:
input_list = [1, 2, 3, 4, 5]
n = 2
result = get_last_n(input_list, n)
print(f"Original list: {input_list}")
print(f"The last {n} elements: {result}")


Original list: [1, 2, 3, 4, 5]
The last 2 elements: [4, 5]


In [ ]:
def reverse_skip(lst):
    """
    Extracts every second element starting from the second-to-last element and moving backward.

    Parameters:
    lst (list): The original list from which elements are extracted.

    Returns:
    list: A list containing every second element starting from the second-to-last element.
    """
    return lst[-2::-2]  # Start from second-to-last element, moving backward, skipping one element in between

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
result = reverse_skip(input_list)
print(f"Original list: {input_list}")
print(f"Reversed and skipped list: {result}")


Original list: [1, 2, 3, 4, 5, 6]
Reversed and skipped list: [5, 3, 1]


Task 4.3

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single list where all elements are in one dimension.

    Parameters:
    lst (list): The nested list to be flattened.

    Returns:
    list: A flattened list with all elements in a single dimension.
    """
    flattened_list = []
    for sublist in lst:
        if isinstance(sublist, list):  # Check if the element is a list
            flattened_list.extend(sublist)  # Add all elements from the sublist
        else:
            flattened_list.append(sublist)  # Add the element if it's not a list
    return flattened_list

# Example usage:
input_list = [[1, 2], [3, 4], [5]]
result = flatten(input_list)
print(f"Original nested list: {input_list}")
print(f"Flattened list: {result}")


Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


In [ ]:
def access_nested_element(lst, indices):
    """
    Extracts an element from a nested list given a list of indices.

    Parameters:
    lst (list): The nested list from which the element is to be extracted.
    indices (list): A list of indices specifying the path to the element.

    Returns:
    The element at the specified position in the nested list.
    """
    element = lst
    for index in indices:
        element = element[index]  # Move to the next level using the index
    return element

# Example usage:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]  # This should access the element 6 (second row, third column)
result = access_nested_element(lst, indices)
print(f"Element at indices {indices}: {result}")


Element at indices [1, 2]: 6


In [ ]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list, regardless of depth.

    Parameters:
    lst (list): The nested list whose elements are to be summed.

    Returns:
    int: The sum of all the numbers in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):  # If the item is a list, recurse into it
            total += sum_nested(item)
        else:
            total += item  # Otherwise, add the number directly
    return total

# Example usage:
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(f"Sum of all elements in the nested list: {result}")


Sum of all elements in the nested list: 21


In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): The nested list from which the element will be removed.
    elem: The element to be removed from the list.

    Returns:
    list: The modified list with all occurrences of the element removed.
    """
    # Iterate over the list and process sublists
    for i in range(len(lst)):
        if isinstance(lst[i], list):  # If it's a sublist, call the function recursively
            lst[i] = remove_element(lst[i], elem)
        else:
            if lst[i] == elem:  # If the element equals the target, remove it
                lst.pop(i)  # Remove the element and update the index
                return remove_element(lst, elem)  # Recursively call to handle further occurrences
    return lst

# Example usage:
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
result = remove_element(lst, elem)
print(f"Modified list after removing {elem}: {result}")


Modified list after removing 2: [[1], [3], [4, 5]]


In [ ]:
def find_max(lst):
    """
    Finds the maximum element in a nested list, regardless of depth.

    Parameters:
    lst (list): The nested list from which to find the maximum element.

    Returns:
    int or float: The maximum element in the list.
    """
    max_value = float('-inf')  # Start with the smallest possible value

    for item in lst:
        if isinstance(item, list):  # If it's a sublist, recurse into it
            max_value = max(max_value, find_max(item))
        else:
            max_value = max(max_value, item)  # Compare with the current max_value

    return max_value

# Example usage:
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(f"The maximum element in the nested list is: {result}")


The maximum element in the nested list is: 6


In [ ]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): The nested list in which to count occurrences of elem.
    elem: The element whose occurrences are to be counted.

    Returns:
    int: The number of times elem appears in the nested list.
    """
    count = 0  # Initialize a counter

    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, recurse into it
            count += count_occurrences(item, elem)
        else:
            if item == elem:  # If the item matches elem, increment the count
                count += 1

    return count

# Example usage:
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
result = count_occurrences(lst, elem)
print(f"The element {elem} appears {result} times in the nested list.")


The element 2 appears 3 times in the nested list.


In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list, regardless of depth.

    Parameters:
    lst (list): The deeply nested list to be flattened.

    Returns:
    list: A flattened version of the list.
    """
    flattened = []  # Initialize an empty list to store the flattened elements

    for item in lst:
        if isinstance(item, list):  # If the item is a list, recursively flatten it
            flattened.extend(deep_flatten(item))
        else:
            flattened.append(item)  # If the item is not a list, add it to the flattened list

    return flattened

# Example usage:
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(f"Flattened list: {result}")


Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list): The nested list whose elements' average is to be calculated.

    Returns:
    float: The average of all elements in the nested list.
    """
    total = 0
    count = 0

    # Helper function to iterate through the nested list
    def flatten_and_count(sub_lst):
        nonlocal total, count
        for item in sub_lst:
            if isinstance(item, list):
                flatten_and_count(item)  # Recurse if item is a sublist
            else:
                total += item
                count += 1

    flatten_and_count(lst)

    # Calculate and return the average
    if count == 0:  # Prevent division by zero
        return 0
    return total / count

# Example usage:
nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(f"The average of all elements in the nested list is: {result}")


The average of all elements in the nested list is: 3.5


In [ ]:
import numpy as np
# initialize an all zero array with size 2 X 3:
zeros_arr = np.zeros((2,3))
print(" A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



Task 10 problems

In [ ]:
import numpy as np

# Task 1: Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty array (2x2):")
print(empty_array)

# Task 2: Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll ones array (4x2):")
print(ones_array)

# Task 3: Return a new array of given shape and type, filled with a fill value (e.g., fill_value = 7)
fill_value_array = np.full((3, 3), 7)  # Example with shape 3x3 and fill value 7
print("\nArray filled with value 7 (3x3):")
print(fill_value_array)

# Task 4: Return a new array of zeros with the same shape and type as a given array
existing_array = np.array([[1, 2], [3, 4]])  # Example existing array
zeros_like_array = np.zeros_like(existing_array)
print("\nArray of zeros like the existing array:")
print(zeros_like_array)

# Task 5: Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(existing_array)
print("\nArray of ones like the existing array:")
print(ones_like_array)

# Task 6: Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array_from_list = np.array(new_list)
print("\nNumPy array from existing list:")
print(numpy_array_from_list)


Empty array (2x2):
[[1.64981454e-316 0.00000000e+000]
 [5.33196831e-317 5.33196831e-317]]

All ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with value 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Array of zeros like the existing array:
[[0 0]
 [0 0]]

Array of ones like the existing array:
[[1 1]
 [1 1]]

NumPy array from existing list:
[1 2 3 4]


In [ ]:
import numpy as np

# Task 1: Create an array with values ranging from 10 to 49.
arr1 = np.arange(10, 50)
print("Array with values ranging from 10 to 49:")
print(arr1)

# Task 2: Create a 3X3 matrix with values ranging from 0 to 8.
arr2 = np.arange(9).reshape(3, 3)
print("\n3X3 matrix with values ranging from 0 to 8:")
print(arr2)

# Task 3: Create a 3X3 identity matrix.
identity_matrix = np.eye(3)
print("\n3X3 identity matrix:")
print(identity_matrix)

# Task 4: Create a random array of size 30 and find the mean of the array.
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30 and its mean:")
print(random_array)
print(f"Mean of the array: {mean_value}")

# Task 5: Create a 10X10 array with random values and find the minimum and maximum values.
random_10x10_array = np.random.random((10, 10))
min_value = random_10x10_array.min()
max_value = random_10x10_array.max()
print("\n10X10 random array and its min and max values:")
print(random_10x10_array)
print(f"Min value: {min_value}")
print(f"Max value: {max_value}")

# Task 6: Create a zero array of size 10 and replace 5th element with 1.
arr6 = np.zeros(10)
arr6[4] = 1  # 5th element is at index 4
print("\nZero array with 5th element replaced by 1:")
print(arr6)

# Task 7: Reverse an array arr = [1, 2, 0, 0, 4, 0].
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr7[::-1]
print("\nReversed array:")
print(reversed_arr)

# Task 8: Create a 2D array with 1 on the border and 0 inside.
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:")
print(arr8)

# Task 9: Create an 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8X8 matrix filled with a checkerboard pattern:")
print(checkerboard)


Array with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3X3 matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3X3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30 and its mean:
[0.88354471 0.95111703 0.90087521 0.66652406 0.60859809 0.02870414
 0.96934206 0.98702074 0.1882869  0.85474589 0.08930207 0.7521972
 0.91640405 0.24795393 0.71263274 0.51218905 0.31175165 0.0955149
 0.15508841 0.92200359 0.54293529 0.17105811 0.12263019 0.89447868
 0.5314487  0.87986028 0.61760683 0.98220137 0.22339578 0.09328544]
Mean of the array: 0.5604232363736024

10X10 random array and its min and max values:
[[0.6917981  0.22890654 0.93197065 0.75061406 0.72102809 0.76708275
  0.97684716 0.75015559 0.84190594 0.62739853]
 [0.78756529 0.32135288 0.38828595 0.9572739  0.30282288 0.06623474
  0.75416866 0.9235336  0.74327319 0.81068839]
 [0.14745639 0.

In [ ]:
import numpy as np

# Arrays given:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1: Add the two arrays
add_result = x + y
print("1. Addition of x and y:")
print(add_result)

# Task 2: Subtract the two arrays
subtract_result = x - y
print("\n2. Subtraction of x and y:")
print(subtract_result)

# Task 3: Multiply the array with any integers of your choice (let's use 2)
multiply_result = x * 2
print("\n3. Multiplying x by 2:")
print(multiply_result)

# Task 4: Find the square of each element of the array
square_result = np.square(x)
print("\n4. Square of each element of x:")
print(square_result)

# Task 5: Find the dot product between v and w; x and v; x and y
dot_product_vw = np.dot(v, w)
dot_product_xv = np.dot(x, v)
dot_product_xy = np.dot(x, y)

print("\n5. Dot product between v and w:", dot_product_vw)
print("Dot product between x and v:")
print(dot_product_xv)
print("Dot product between x and y:")
print(dot_product_xy)

# Task 6: Concatenate x and y along row and v and w along column
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print("\n6. Concatenate x and y along rows:")
print(concat_xy_row)
print("Concatenate v and w along columns:")
print(concat_vw_column)

# Task 7: Concatenate x and v; if you get an error, observe and explain why
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n7. Concatenate x and v along rows:")
    print(concat_xv)
except Exception as e:
    print("\n7. Error when concatenating x and v along rows:")
    print(e)


1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiplying x by 2:
[[ 2  4]
 [ 6 10]]

4. Square of each element of x:
[[ 1  4]
 [ 9 25]]

5. Dot product between v and w: 219
Dot product between x and v:
[29 77]
Dot product between x and y:
[[19 22]
 [50 58]]

6. Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
[[ 9 11]
 [10 12]]

7. Error when concatenating x and v along rows:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
import numpy as np

# Given matrices:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I (Identity matrix)
A_inv = np.linalg.inv(A)  # Calculate the inverse of A
I = np.dot(A, A_inv)  # Multiply A with its inverse to get the identity matrix
print("1. Prove A * A^-1 = I:")
print(I)

# 2. Prove AB != BA (Matrix multiplication is not commutative)
AB = np.dot(A, B)  # AB
BA = np.dot(B, A)  # BA
print("\n2. Prove AB != BA:")
print("AB:")
print(AB)
print("BA:")
print(BA)

# Check if AB is equal to BA
if np.array_equal(AB, BA):
    print("AB is equal to BA")
else:
    print("AB is not equal to BA")

# 3. Prove (AB)^T = B^T * A^T (Transpose property)
AB_T = np.transpose(AB)  # (AB)^T
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))  # B^T * A^T
print("\n3. Prove (AB)^T = B^T * A^T:")
print("Transpose of AB:")
print(AB_T)
print("B^T * A^T:")
print(B_T_A_T)


# Represent the system as AX = B
# A is the coefficient matrix, X is the variables [x, y, z], and B is the constant matrix.
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficients of the system
B_eq = np.array([-1, -3, 9])  # Constants on the right-hand side of the equations

# Solve for X (the solution vector [x, y, z])
X = np.linalg.solve(A_eq, B_eq)
print("\nSolution to the system of linear equations (using np.linalg.solve):")
print(f"x = {X[0]}, y = {X[1]}, z = {X[2]}")

# Alternatively, use the inverse method to solve AX = B
A_inv_eq = np.linalg.inv(A_eq)  # Inverse of A_eq
X_inv_method = np.dot(A_inv_eq, B_eq)  # X = A_inv * B
print("\nSolution to the system of linear equations (using inverse method):")
print(f"x = {X_inv_method[0]}, y = {X_inv_method[1]}, z = {X_inv_method[2]}")


1. Prove A * A^-1 = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. Prove AB != BA:
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
AB is not equal to BA

3. Prove (AB)^T = B^T * A^T:
Transpose of AB:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]

Solution to the system of linear equations (using np.linalg.solve):
x = 2.0, y = 1.0000000000000002, z = -2.0

Solution to the system of linear equations (using inverse method):
x = 2.0, y = 1.0, z = -2.0


task10.2

In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000, 2000000)]

# Measure the time taken for element-wise addition of two lists
start_time = time.time()

# Element-wise addition using list comprehension
result_list = [list1[i] + list2[i] for i in range(1000000)]

end_time = time.time()
print(f"Time taken for element-wise addition using Python lists: {end_time - start_time} seconds")


Time taken for element-wise addition using Python lists: 0.25238466262817383 seconds


In [ ]:
import numpy as np

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000, 2000000)

# Measure the time taken for element-wise addition of two NumPy arrays
start_time = time.time()

# Element-wise addition using NumPy
result_array = array1 + array2

end_time = time.time()
print(f"Time taken for element-wise addition using NumPy arrays: {end_time - start_time} seconds")


Time taken for element-wise addition using NumPy arrays: 0.007414579391479492 seconds


In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000, 2000000)]

# Measure the time taken for element-wise multiplication of two lists
start_time = time.time()

# Element-wise multiplication using list comprehension
result_list = [list1[i] * list2[i] for i in range(1000000)]

end_time = time.time()
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time} seconds")


Time taken for element-wise multiplication using Python lists: 0.15629816055297852 seconds


In [ ]:
import numpy as np

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000, 2000000)

# Measure the time taken for element-wise multiplication of two NumPy arrays
start_time = time.time()

# Element-wise multiplication using NumPy
result_array = array1 * array2

end_time = time.time()
print(f"Time taken for element-wise multiplication using NumPy arrays: {end_time - start_time} seconds")


Time taken for element-wise multiplication using NumPy arrays: 0.004985332489013672 seconds


In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000, 2000000)]

# Measure the time taken for the dot product of two lists
start_time = time.time()

# Dot product using list comprehension
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))

end_time = time.time()
print(f"Time taken for dot product using Python lists: {end_time - start_time} seconds")


Time taken for dot product using Python lists: 0.18314170837402344 seconds


In [ ]:
import numpy as np

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000, 2000000)

# Measure the time taken for the dot product of two NumPy arrays
start_time = time.time()

# Dot product using NumPy
dot_product_array = np.dot(array1, array2)

end_time = time.time()
print(f"Time taken for dot product using NumPy arrays: {end_time - start_time} seconds")


Time taken for dot product using NumPy arrays: 0.0021212100982666016 seconds


In [ ]:
import numpy as np

# Create two 1000x1000 matrices using NumPy
matrix1_np = np.random.rand(1000, 1000)
matrix2_np = np.random.rand(1000, 1000)

# Measure the time taken for matrix multiplication using NumPy arrays
start_time = time.time()

# Matrix multiplication using NumPy's dot method
result_np = np.dot(matrix1_np, matrix2_np)

end_time = time.time()
print(f"Time taken for matrix multiplication using NumPy arrays: {end_time - start_time} seconds")


Time taken for matrix multiplication using NumPy arrays: 0.10885071754455566 seconds
